# TODO: Change to `next/core-web-vitals` once ready to tackle perf
extends: "next"
rules:
  
  # TODO: Supply AltText if possible 
  jsx-a11y/alt-text: off

  # TODO: Change back to error and correct
  react/jsx-key: 
    - off
    - checkFragmentShorthand: true

  # Disabled because Evergreen-UI components don't have display names
  react/display-name: off