name: CI Test

on: [ workflow_dispatch ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*" 
          cache: "yarn"

      - name: Run tests
        run: |
          yarn
          yarn test
